/**
 * @file  rivr_dispatch.c
 * @brief Egress fanout policy implementation.
 */

#include "rivr_dispatch.h"

/* ── App-relevance filter ──────────────────────────────────────────────── */

bool rivr_dispatch_is_app_relevant(uint8_t pkt_type)
{
    switch (pkt_type) {
        case PKT_CHAT:      /* fall-through */
        case PKT_BEACON:    /* fall-through */
        case PKT_DATA:      /* fall-through */
        case PKT_TELEMETRY: /* fall-through */
        case PKT_MAILBOX:   /* fall-through */
        case PKT_ALERT:     /* fall-through */
        case PKT_PRIVATE_CHAT:       /* private 1-to-1 messages are app-relevant */
        case PKT_DELIVERY_RECEIPT:   /* delivery receipts must reach the app */
            return true;

        case PKT_ROUTE_REQ: /* mesh-internal routing control — not for clients */
        case PKT_ROUTE_RPL:
        case PKT_ACK:
        case PKT_PROG_PUSH:
        default:
            return false;
    }
}

/* ── Egress fanout policy ─────────────────────────────────────────────── */

rivr_iface_mask_t rivr_dispatch_select(uint8_t pkt_type, rivr_iface_t source)
{
    bool app = rivr_dispatch_is_app_relevant(pkt_type);

    switch (source) {
        case RIVR_IFACE_LORA:
            /* Mirror app traffic to all host-facing transports.
             * LoRa→LoRa relay is handled by routing_flood_forward, not bus. */
            if (app) {
                return RIVR_MASK_BLE | RIVR_MASK_USB;
            }
            return RIVR_MASK_NONE;

        case RIVR_IFACE_BLE:
            /* Mirror to USB bridge if active.
             * BLE→LoRa relay: routing_flood_forward handles it automatically
             * because the frame enters the mesh pipeline via rf_rx_ringbuf. */
            if (app) {
                return RIVR_MASK_USB;
            }
            return RIVR_MASK_NONE;

        case RIVR_IFACE_USB:
            /* Mirror to BLE client if connected.
             * USB→LoRa relay: same as BLE, routing handles it. */
            if (app) {
                return RIVR_MASK_BLE;
            }
            return RIVR_MASK_NONE;

        case RIVR_IFACE_WIFI:
            /* Future transport — same mirroring policy as LoRa for now. */
            if (app) {
                return RIVR_MASK_BLE | RIVR_MASK_USB;
            }
            return RIVR_MASK_NONE;

        case RIVR_IFACE_LOCAL:
            /* Frame generated by this node's program layer.
             * Inject into all physical transports regardless of type. */
            return RIVR_MASK_LORA | RIVR_MASK_BLE | RIVR_MASK_USB;

        default:
            return RIVR_MASK_NONE;
    }
}
